export class UsuarioJefeList {
  acreedor?: number;
  activo?: number;
  aprobacion?: number;
  descuento_pp?: number;
  fecha_cierre?: number;
  id?: number;
  origen_portal?: number;
  pais?: number;
  password?: number;
  persona_fisica?: number;
  proveedor?: number;
  reset_password?: number;
  token?: number;
  ultima_actualizacion?: number;
  email?: string;
  email_alterno?: string;
  fecha_creacion?: string;
  identificador_aprobador?: string;
  identificador_centro_costo?: string;
  identificador_contribuyente?: string;
  identificador_corporativo?: string;
  identificador_empleado?: string;
  identificador_usuario?: string;
  nombre?: string;
  nombre_aprobador?: string;
  numero_empleado?: string;
  numero_proveedor?: string;
}
